name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
 

    steps:
    - uses: actions/checkout@v2
    - name: Install Cmake
      run: sudo apt-get install cmake
    - name: Configure
      run: mkdir build && cd build  && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: Build
      run:  cmake --build build
    - name: Test
      run: cd build && ctest
    - name: make
      run: make
